[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nit"
version = "0.0.1"
authors = [
  { name="MossTeK" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: NixOS",
]

[project.urls]
Homepage = "https://github.com/MossTeK/nit"
Issues = "https://github.com/MossTeK/nit/issues"